apiVersion: v1
kind: Service
metadata:
  name: {{ include "webring.fullname" . }}-api
  labels:
    {{- include "webring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}-api
      targetPort: http-api
      protocol: TCP
      name: http-api
  selector:
    {{- include "webring.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webring.fullname" . }}-frontend
  labels:
    {{- include "webring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}-frontend
      targetPort: http-frontend
      protocol: TCP
      name: http-frontend
  selector:
    {{- include "webring.selectorLabels" . | nindent 4 }}
